#https://stackoverflow.com/questions/60853414/python-celery-trying-to-occupy-a-port-number-in-docker-compose-and-creating-prob

services:
  common-api-settings: &api-settings
    build: 
        context: . #root directory
        dockerfile: ./docker/local/django/Dockerfile
    volumes:
      - /home/projects/django/estate-management/django:/app:z
      - staticfiles:/app/staticfiles:z
    env_file:
      - ./.envs/.env.local
    depends_on:
      - postgres
      - mailpit
    networks:
      - estate_network
  api: 
    <<: *api-settings
    image: estate_prod_api
    container_name: estate_prod_api
    ports:
      - "8003:8000"
    command: /start

  postgres:
    build: 
      context: . #root directory
      dockerfile: ./docker/local/postgres/Dockerfile
    image: estate_prod_postgres
    container_name: estate_prod_postgres
    volumes:
      - estate_postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    env_file:
      - ./.envs/.env.local
    networks:
      - estate_network
  
  redis:
    image: redis:7.0-alpine3.19
    command: ["redis-server", "--appendonly", "yes"]
    container_name: estate_redis
    volumes:
      - estate_redis_data:/data
    ports:
      - "6380:6379"
    networks:
      - estate_network

  celeryworker:
    <<: *api-settings
    image: estate_celeryworker
    command: /start-celeryworker
    container_name: estate_celeryworker

  celerybeat:
    <<: *api-settings
    image: estate_celerybeat
    command: /start-celerybeat
    container_name: estate_celerybeat

  flower:
    <<: *api-settings
    image: estate_flower
    command: /start-flower
    container_name: estate_flower
    ports:
      - "5555:5555"

  mailpit:
    image: axllent/mailpit
    container_name: estate_prod_mailpit
    volumes:
      - estate_mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    ports:
      - "8025:8025"
    networks:
      - estate_network

networks:
  estate_network:
    driver: bridge
    external: true

volumes: 
  estate_postgres_data: {}
  estate_mailpit_data: {}
  staticfiles: {}
  estate_redis_data: {}
