# Generated by Django 5.1.2 on 2024-11-19 02:34

import autoslug.fields
import cloudinary.models
import core_apps.profiles.models
import django_countries.fields
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("student", "Student"),
                            ("employed", "Employed"),
                            ("unemployed", "Unemployed"),
                            ("retired", "Retired"),
                            ("tenant", "Tenant"),
                            ("freelancer", "Freelancer"),
                            ("other", "Other"),
                        ],
                        default="tenant",
                        max_length=100,
                        verbose_name="Occupation",
                    ),
                ),
                (
                    "avatar",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="Avatar"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Bio")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, default="VN", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="City"),
                ),
                (
                    "report_count",
                    models.PositiveIntegerField(default=0, verbose_name="Report Count"),
                ),
                (
                    "reputation",
                    models.IntegerField(default=100, verbose_name="Reputation"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=core_apps.profiles.models.get_user_username,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
