# Generated by Django 5.1.2 on 2024-11-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="city",
            new_name="city_of_origin",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="country",
            new_name="country_of_origin",
        ),
    ]
